[workspace]
members = ["lluda-inference"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Alex Makeev <alex@makeev.dev>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/alexmakeev/qwen-omni-inference-rs"
